// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://rjppowrrabshtnbfigzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqcHBvd3JyYWJzaHRuYmZpZ3piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NjczNDAsImV4cCI6MjA3NDM0MzM0MH0.GzU0oKipRVsolcLwc_OXwZAEuNvvKK6zeSqsH0-7y7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // Performance optimizations
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'X-Client-Info': 'admin-user-manager'
    }
  },
  // Optimize for real-time subscriptions if needed
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});
